#!/bin/sh

mkdir opk/
git pull
./submodule_update.sh
cp icons/picodrive.png opk/
cp AUTHORS COPYING README opk/
cp picodrive.sh opk/

cd /opt/FunKey-OS
rm -rf FunKey/output/build/picodrive-*
sed -i 's|PICODRIVE_OVERRIDE_SRCDIR.*|PICODRIVE_OVERRIDE_SRCDIR = /opt/picodrive-funkey|' /opt/FunKey-OS/FunKey/output/local.mk
git pull
make
cp FunKey/output/target/usr/games/PicoDrive /opt/picodrive-funkey/opk
cd -

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GMenu2X entry file plus other things

print '[Desktop Entry]
Name=Mega Drive
Comment=MS/MD/MCD/32X emulator
Exec=picodrive.sh %f
Icon=picodrive
Categories=emulators;
SelectorFilter=zip,md,smd,sms,32x,cue,cso,chd' > opk/picodrive.funkey-s.desktop

rm -f *.opk
mksquashfs opk/ picodrive_v1.98_$(md5sum opk/PicoDrive | cut -c1-7)_funkey-s.opk -all-root -noappend -no-exports -no-xattrs

rm -rf opk/
