name: CI (GP2X)
on: [push, pull_request]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install dependencies
      run: |
        whoami
        sudo apt-get update -qq
        sudo apt-get install -y wget
        wget http://notaz.gp2x.de/downloads/gp2x/devkitGP2X_small.tar.xz
        tar -C /tmp/ -xf devkitGP2X_small.tar.xz
    - name: configure
      run: DUMP_CONFIG_LOG=1 PATH=$PATH:/tmp/devkitGP2X/bin CROSS_COMPILE=arm-linux- ./configure --platform=gp2x
    - name: make
      run: PATH=$PATH:/tmp/devkitGP2X/bin CROSS_COMPILE=arm-linux- make PLATFORM_MP3=0
