name: CI (Linux)
on: [push, pull_request]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y libsdl1.2-dev libasound2-dev libpng-dev libz-dev
    - name: configure
      run: DUMP_CONFIG_LOG=1 ./configure
    - name: make
      run: make
